import os

# Capture directory
target_dir = input(r'Enter target directory: ')

# Change to target directory.
os.chdir(target_dir)

# Get game name.
game_name = input(r'Enter game name (separated by hyphens): ')

# Create folder with a Pictures folder inside.
os.mkdir(game_name)

# Change to new directory
os.chdir(target_dir + "\\" + game_name)

# Make a Pictures folder.
os.mkdir("Pictures")

# Get game abbreviation
game_abbreviation = input(r'Enter game abbreviation: ')

### Create aspx file.
aspx = f'''

<%@ Page Title="" Language="vb" AutoEventWireup="false" MasterPageFile="~/Site.Master" CodeBehind="{game_name}.aspx.vb" Inherits="thephooniverse.{game_name}" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server"></asp:Content>

<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">

    <script type="text/javascript">

        $(document).ready(function () {{
            imageSource("{game_name}");
        }});

    </script>

    <div class='image-select hide'></div>

    <h1 class="game-title {game_abbreviation}">
        {game_name}
    </h1>

    <h2 class="header-text">
        Images
    </h2>

    <div class="image-list">

    </div>

</asp:Content>

'''

### Create aspx.designer.vb
designer = f'''

'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



Partial Public Class {game_name}
End Class

'''

### Create aspx.vb
vb = f'''

Public Class {game_name}
    Inherits System.Web.UI.Page

    Protected Sub Page_Load(ByVal sender As Object, ByVal e As System.EventArgs) Handles Me.Load

    End Sub

End Class

'''

### Actually create the files.
with open(f'{game_name}.aspx', 'w') as f:
    f.write(aspx)

with open(f'{game_name}.aspx.designer.vb', 'w') as f:
    f.write(designer)

with open(f'{game_name}.aspx.vb', 'w') as f:
    f.write(vb)
